CREATE TABLE IF NOT EXISTS public.applicants
(
    applicant_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    first_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    has_applied boolean NOT NULL DEFAULT FALSE,
    is_selected boolean NOT NULL DEFAULT FALSE,
    last_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    registration_timestamp timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    timezone character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Europe/Chisinau',
    project_id bigint NOT NULL,
    team_id bigint,
    user_id bigint,
    CONSTRAINT PK_Applicants PRIMARY KEY (applicant_id),
    CONSTRAINT FK_applicants_team_id FOREIGN KEY (team_id)
        REFERENCES public.teams (team_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT FK_Applicants_project_id FOREIGN KEY (project_id)
        REFERENCES public.projects (project_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)