CREATE TABLE IF NOT EXISTS public.form_questions
(
    created_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    question character varying(1000)  NOT NULL,
    question_number integer NOT NULL,
    question_type character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    project_id bigint NOT NULL,
    question_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    checkbox_options character varying(1000),
    CONSTRAINT pk_form_questions PRIMARY KEY (question_id),
    CONSTRAINT fk_form_questions_project_id FOREIGN KEY (project_id)
        REFERENCES public.projects (project_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT form_questions_question_type_check CHECK (question_type::text = ANY (ARRAY['FILE'::character varying, 'CHECKBOX'::character varying, 'TEXT'::character varying]::text[]))
)