CREATE TABLE IF NOT EXISTS public.question_answers
(
    question_answer_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    question_answer character varying(5000),
    applicant_id bigint NOT NULL,
    question_id bigint NOT NULL,
    CONSTRAINT pk_question_answers PRIMARY KEY (question_answer_id),
    CONSTRAINT fk_question_answers_applicants_id FOREIGN KEY (applicant_id)
        REFERENCES public.applicants (applicant_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_question_answers_question_id FOREIGN KEY (question_id)
        REFERENCES public.form_questions (question_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
