CREATE TABLE IF NOT EXISTS public.teams
(
    team_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date_created timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated timestamp(6) with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    team_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    project_id bigint NOT NULL,
    CONSTRAINT pk_teams PRIMARY KEY (team_id),
    CONSTRAINT team_name_project_id UNIQUE (team_name, project_id),
    CONSTRAINT fk_teams_project_id FOREIGN KEY (project_id)
        REFERENCES public.projects (project_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)