CREATE TABLE team_member_backgrounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    background_code VARCHAR(255) NOT NULL,

    CONSTRAINT fk_team_member_backgrounds_team
    FOREIGN KEY (team_id)
        REFERENCES teams(team_id),

    CONSTRAINT fk_team_member_backgrounds_member
    FOREIGN KEY (member_id)
        REFERENCES team_members(id)
);